/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications.index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as AuthorsIndexRouteImport } from './routes/authors.index'
import { Route as TopicsDomainRouteImport } from './routes/topics.domain'
import { Route as TopicsTopicIdRouteImport } from './routes/topics.$topicId'
import { Route as PapersIdRouteImport } from './routes/papers.$id'
import { Route as NotificationsGroupIdRouteImport } from './routes/notifications.$groupId'
import { Route as CollectionsCollectionIdRouteImport } from './routes/collections.$collectionId'
import { Route as AuthorsAuthorIdRouteImport } from './routes/authors.$authorId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as TopicsDomainDomainRouteImport } from './routes/topics.domain.$domain'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotificationsRoute,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionsRoute,
} as any)
const AuthorsIndexRoute = AuthorsIndexRouteImport.update({
  id: '/authors/',
  path: '/authors/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsDomainRoute = TopicsDomainRouteImport.update({
  id: '/topics/domain',
  path: '/topics/domain',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdRoute = TopicsTopicIdRouteImport.update({
  id: '/topics/$topicId',
  path: '/topics/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersIdRoute = PapersIdRouteImport.update({
  id: '/papers/$id',
  path: '/papers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsGroupIdRoute = NotificationsGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => NotificationsRoute,
} as any)
const CollectionsCollectionIdRoute = CollectionsCollectionIdRouteImport.update({
  id: '/$collectionId',
  path: '/$collectionId',
  getParentRoute: () => CollectionsRoute,
} as any)
const AuthorsAuthorIdRoute = AuthorsAuthorIdRouteImport.update({
  id: '/authors/$authorId',
  path: '/authors/$authorId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const TopicsDomainDomainRoute = TopicsDomainDomainRouteImport.update({
  id: '/$domain',
  path: '/$domain',
  getParentRoute: () => TopicsDomainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookmarks': typeof BookmarksRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forecast': typeof ForecastRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/trends': typeof TrendsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/users': typeof AdminUsersRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/notifications/$groupId': typeof NotificationsGroupIdRoute
  '/papers/$id': typeof PapersIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/topics/domain': typeof TopicsDomainRouteWithChildren
  '/authors/': typeof AuthorsIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/topics/domain/$domain': typeof TopicsDomainDomainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookmarks': typeof BookmarksRoute
  '/dashboard': typeof DashboardRoute
  '/forecast': typeof ForecastRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/trends': typeof TrendsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/users': typeof AdminUsersRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/notifications/$groupId': typeof NotificationsGroupIdRoute
  '/papers/$id': typeof PapersIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/topics/domain': typeof TopicsDomainRouteWithChildren
  '/authors': typeof AuthorsIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/topics/domain/$domain': typeof TopicsDomainDomainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookmarks': typeof BookmarksRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forecast': typeof ForecastRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/trends': typeof TrendsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/users': typeof AdminUsersRoute
  '/authors/$authorId': typeof AuthorsAuthorIdRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/notifications/$groupId': typeof NotificationsGroupIdRoute
  '/papers/$id': typeof PapersIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/topics/domain': typeof TopicsDomainRouteWithChildren
  '/authors/': typeof AuthorsIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/topics/domain/$domain': typeof TopicsDomainDomainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bookmarks'
    | '/collections'
    | '/dashboard'
    | '/forecast'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/search'
    | '/trends'
    | '/verify-email'
    | '/admin/users'
    | '/authors/$authorId'
    | '/collections/$collectionId'
    | '/notifications/$groupId'
    | '/papers/$id'
    | '/topics/$topicId'
    | '/topics/domain'
    | '/authors/'
    | '/collections/'
    | '/notifications/'
    | '/topics/domain/$domain'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bookmarks'
    | '/dashboard'
    | '/forecast'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/search'
    | '/trends'
    | '/verify-email'
    | '/admin/users'
    | '/authors/$authorId'
    | '/collections/$collectionId'
    | '/notifications/$groupId'
    | '/papers/$id'
    | '/topics/$topicId'
    | '/topics/domain'
    | '/authors'
    | '/collections'
    | '/notifications'
    | '/topics/domain/$domain'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bookmarks'
    | '/collections'
    | '/dashboard'
    | '/forecast'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/search'
    | '/trends'
    | '/verify-email'
    | '/admin/users'
    | '/authors/$authorId'
    | '/collections/$collectionId'
    | '/notifications/$groupId'
    | '/papers/$id'
    | '/topics/$topicId'
    | '/topics/domain'
    | '/authors/'
    | '/collections/'
    | '/notifications/'
    | '/topics/domain/$domain'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookmarksRoute: typeof BookmarksRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForecastRoute: typeof ForecastRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  TrendsRoute: typeof TrendsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthorsAuthorIdRoute: typeof AuthorsAuthorIdRoute
  PapersIdRoute: typeof PapersIdRoute
  TopicsTopicIdRoute: typeof TopicsTopicIdRoute
  TopicsDomainRoute: typeof TopicsDomainRouteWithChildren
  AuthorsIndexRoute: typeof AuthorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof NotificationsRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/authors/': {
      id: '/authors/'
      path: '/authors'
      fullPath: '/authors/'
      preLoaderRoute: typeof AuthorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/domain': {
      id: '/topics/domain'
      path: '/topics/domain'
      fullPath: '/topics/domain'
      preLoaderRoute: typeof TopicsDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicId': {
      id: '/topics/$topicId'
      path: '/topics/$topicId'
      fullPath: '/topics/$topicId'
      preLoaderRoute: typeof TopicsTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/$id': {
      id: '/papers/$id'
      path: '/papers/$id'
      fullPath: '/papers/$id'
      preLoaderRoute: typeof PapersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/$groupId': {
      id: '/notifications/$groupId'
      path: '/$groupId'
      fullPath: '/notifications/$groupId'
      preLoaderRoute: typeof NotificationsGroupIdRouteImport
      parentRoute: typeof NotificationsRoute
    }
    '/collections/$collectionId': {
      id: '/collections/$collectionId'
      path: '/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof CollectionsCollectionIdRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/authors/$authorId': {
      id: '/authors/$authorId'
      path: '/authors/$authorId'
      fullPath: '/authors/$authorId'
      preLoaderRoute: typeof AuthorsAuthorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/topics/domain/$domain': {
      id: '/topics/domain/$domain'
      path: '/$domain'
      fullPath: '/topics/domain/$domain'
      preLoaderRoute: typeof TopicsDomainDomainRouteImport
      parentRoute: typeof TopicsDomainRoute
    }
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CollectionsRouteChildren {
  CollectionsCollectionIdRoute: typeof CollectionsCollectionIdRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsCollectionIdRoute: CollectionsCollectionIdRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface NotificationsRouteChildren {
  NotificationsGroupIdRoute: typeof NotificationsGroupIdRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
}

const NotificationsRouteChildren: NotificationsRouteChildren = {
  NotificationsGroupIdRoute: NotificationsGroupIdRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
}

const NotificationsRouteWithChildren = NotificationsRoute._addFileChildren(
  NotificationsRouteChildren,
)

interface TopicsDomainRouteChildren {
  TopicsDomainDomainRoute: typeof TopicsDomainDomainRoute
}

const TopicsDomainRouteChildren: TopicsDomainRouteChildren = {
  TopicsDomainDomainRoute: TopicsDomainDomainRoute,
}

const TopicsDomainRouteWithChildren = TopicsDomainRoute._addFileChildren(
  TopicsDomainRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookmarksRoute: BookmarksRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForecastRoute: ForecastRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  TrendsRoute: TrendsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthorsAuthorIdRoute: AuthorsAuthorIdRoute,
  PapersIdRoute: PapersIdRoute,
  TopicsTopicIdRoute: TopicsTopicIdRoute,
  TopicsDomainRoute: TopicsDomainRouteWithChildren,
  AuthorsIndexRoute: AuthorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
